---
- hosts: dev
  tasks:
    - name: "DEV BUILD : Facts : Get username for perms"
      local_action: command whoami
      register: username
    - name: "DEV BUILD : Infrastructure : Docker : Create Networks"
      docker_network:
        name: ps2alerts
        state: present

    - name: "DEV BUILD : Infrastructure : Create NGINX log dir"
      file:
        path: logs/nginx
        state: directory
        mode: 0777

    - name: "DEV BUILD : Infrastructure : Create / Flush NGINX logs"
      copy:
        content: ""
        dest: logs/nginx/{{ item }}
        force: yes
      with_items:
        - access.log
        - error.log

    - name: "DEV BUILD : Dependencies : Composer : Install"
      docker_container:
        name: ps2alerts-website-composer
        image: composer:latest
        volumes:
          - ../../:/app
        command: install
        user: 1000:1000
        auto_remove: yes

    - name: "DEV BUILD : Dependencies : npm : Install"
      docker_container:
        name: ps2alerts-website-npm
        image: digitallyseamless/nodejs-bower-grunt
        volumes:
          - ../../:/src:rw
        working_dir: "/src"
        command: "npm install"
        user: 1000:1000
        auto_remove: yes

    - name: "DEV BUILD : Environment : Grunt : env"
      docker_container:
        name: ps2alerts-website-grunt-env
        image: digitallyseamless/nodejs-bower-grunt
        volumes:
          - ../../:/src:rw
        working_dir: "/src"
        command: "grunt envDev"
        user: 1000:1000
        auto_remove: yes

    - name: "DEV BUILD : Environment : Grunt : watch"
      docker_container:
        name: ps2alerts-website-grunt-watch
        image: digitallyseamless/nodejs-bower-grunt
        volumes:
          - ../../:/src:rw
        working_dir: "/src"
        command: "grunt watch"
        user: 1000:1000

    - name: "DEV BUILD: Environment : Inject .env"
      copy:
        src: env.dist
        dest: ../../.env

    - name: "DEV BUILD : Infrastructure : Docker : Run Containers"
      docker_service:
        project_src: .
        state: present